const String kOtherManufacturer = 'אחר';

const List<String> _kGenericManufacturers = [
  'Apple',
  'Samsung',
  'Sony',
  'LG',
  'Philips',
  'Bosch',
  'Xiaomi',
  'Nike',
  'Adidas',
  'IKEA',
  'אלקטרה',
  'תדיראן',
];

const List<String> _kNotApplicableManufacturers = <String>[];

const Map<String, List<String>> _kManufacturersByCategory = {
  'fashion': [
    'Zara',
    'H&M',
    'Mango',
    'Castro',
    'Fox',
    'Renuar',
    'Golf',
    'TwentyFourSeven',
    'Honigman',
    'Pull&Bear',
    'Bershka',
    'Stradivarius',
    'Massimo Dutti',
    'Uniqlo',
    'COS',
    "Levi's",
    'Tommy Hilfiger',
    'Calvin Klein',
    'Ralph Lauren',
    'Lacoste',
    'Hugo Boss',
    'Guess',
    'Diesel',
    'Gap',
    'American Eagle',
    'Superdry',
    'Desigual',
    'The North Face',
    'Columbia',
    'Timberland',
    'Dr. Martens',
    'Nike',
    'Adidas',
    'Puma',
    'New Balance',
    'Converse',
    'Vans',
    'Skechers',
    'Crocs',
    'Michael Kors',
    'Delta',
  ],
  'electronics': [
    'Apple',
    'Samsung',
    'Xiaomi',
    'Google',
    'OnePlus',
    'Huawei',
    'Honor',
    'Motorola',
    'Nokia',
    'Oppo',
    'Realme',
    'Sony',
    'LG',
    'Lenovo',
    'Dell',
    'HP',
    'ASUS',
    'Acer',
    'MSI',
    'Microsoft',
    'Nintendo',
    'JBL',
    'Bose',
    'Sennheiser',
    'Anker',
    'Logitech',
    'TCL',
    'Hisense',
    'Philips',
    'Panasonic',
    'Toshiba',
    'Sharp',
    'Canon',
    'Nikon',
    'Fujifilm',
    'GoPro',
    'DJI',
    'Garmin',
    'SanDisk',
    'TP-Link',
  ],
  'vehicles': [
    'Toyota',
    'Mazda',
    'Hyundai',
    'Kia',
    'Skoda',
    'Volkswagen',
    'Nissan',
    'Honda',
    'Mitsubishi',
    'Suzuki',
    'Renault',
    'Peugeot',
    'Citroën',
    'Seat',
    'Cupra',
    'Ford',
    'Chevrolet',
    'Opel',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Volvo',
    'Subaru',
    'Jeep',
    'Tesla',
    'MG',
    'BYD',
    'Chery',
    'Geely',
    'Lexus',
    'Mini',
    'Fiat',
    'Alfa Romeo',
    'Dacia',
    'Land Rover',
    'Porsche',
    'Yamaha',
    'Kawasaki',
    'Piaggio',
    'KTM',
  ],
  'real_estate': [
    'אזורים',
    'שיכון ובינוי',
    'אפריקה ישראל מגורים',
    'גינדי החזקות',
    'צרפתי שמעון',
    'י.ח דמרי',
    'ב. יאיר',
    'רוטשטיין',
    'אשדר',
    'אשטרום',
    'מליבו',
    'תדהר',
    'דוניץ',
    'פרשקובסקי',
    'נאות מזרחי',
    'אביב קבוצה',
    'חג׳ג׳',
    'ישראל קנדה',
    'קרסו נדל״ן',
    'אלמוגים',
    'מגה אור',
    'רסקו',
  ],
  'furniture': [
    'IKEA',
    'ביתילי',
    'הום סנטר',
    'ACE',
    'כתר',
    'עמינח',
    'הולנדיה',
    'אורתופדיה',
    'JYSK',
    'BoConcept',
    'Natuzzi',
    'Calligaris',
    'Poliform',
    'Kartell',
    'Vitra',
    'Herman Miller',
    'Steelcase',
    'USM',
    'Muji',
    'Ashley',
    'La-Z-Boy',
    'Tempur',
    'Sealy',
    'Flexform',
    'HAY',
    'Muuto',
    'Zara Home',
  ],
  'home_garden': [
    'אלקטרה',
    'תדיראן',
    'טורנדו',
    'סאוטר',
    'נורמנדה',
    'אמקור',
    'קריסטל',
    'בלומברג',
    'Beko',
    'Bosch',
    'Siemens',
    'Samsung',
    'LG',
    'Whirlpool',
    'Electrolux',
    'AEG',
    'Miele',
    'Candy',
    'Indesit',
    'Ariston',
    'Sharp',
    'Hisense',
    'Midea',
    'Philips',
    'Braun',
    'Kenwood',
    'Moulinex',
    'Tefal',
    'DeLonghi',
    'Nespresso',
    'SodaStream',
    'Dyson',
    'Kärcher',
    'Makita',
    'DeWalt',
    'Hilti',
    'Ryobi',
    'Stanley',
    'Black+Decker',
    'Gardena',
  ],
  'fashion_beauty': [
    "L'Oréal",
    'Maybelline',
    'Revlon',
    'MAC',
    'NYX',
    'Essence',
    'Catrice',
    'Rimmel',
    'Max Factor',
    'Estée Lauder',
    'Clinique',
    'Lancôme',
    'Dior',
    'Chanel',
    'Yves Saint Laurent',
    'Shiseido',
    'Neutrogena',
    'Nivea',
    'Garnier',
    'Vichy',
    'La Roche-Posay',
    'Eucerin',
    'CeraVe',
    'The Ordinary',
    'Bioderma',
    'Avène',
    'Clarins',
    'קרליין',
    'ד״ר פישר',
    'אהבה',
    'סבון',
    'ליין',
    'כריסטינא',
    'Anna Lotan',
    'Moroccanoil',
    'Gillette',
    'Braun',
    'Philips',
    'Panasonic',
    'Remington',
    'Wahl',
    'BaByliss',
    'Wella',
    'Schwarzkopf',
    'Pantene',
  ],
  'sports': [
    'Nike',
    'Adidas',
    'Puma',
    'Under Armour',
    'Reebok',
    'New Balance',
    'ASICS',
    'Mizuno',
    'Salomon',
    'Hoka',
    'Brooks',
    'Saucony',
    'The North Face',
    'Columbia',
    'Decathlon',
    'Wilson',
    'Head',
    'Babolat',
    'Yonex',
    'Spalding',
    'Molten',
    'Speedo',
    'Arena',
    'Everlast',
    'Venum',
    'Garmin',
    'Polar',
    'Suunto',
    'Technogym',
    'Life Fitness',
    'Matrix',
    'NordicTrack',
    'Bowflex',
    'Kettler',
    'Trek',
    'Giant',
    'Specialized',
    'Scott',
    'Merida',
  ],
  'toys': [
    'LEGO',
    'Playmobil',
    'Hasbro',
    'Mattel',
    'Fisher-Price',
    'Hot Wheels',
    'Nerf',
    'Play-Doh',
    'Barbie',
    'Melissa & Doug',
    'VTech',
    'Little Tikes',
    'Step2',
    'Bruder',
    'Schleich',
    'Ravensburger',
    'Clementoni',
    'Spin Master',
    'MGA',
    'Funko',
    'Bandai',
    'Tomy',
    'Zuru',
    'Simba',
    'Smoby',
    'Djeco',
    'Hape',
    'Tiny Love',
    'Taf Toys',
    'Nintendo',
    'Sony',
    'Microsoft',
  ],
  'kids': [
    'Chicco',
    'Maxi-Cosi',
    'Britax',
    'Cybex',
    'Joie',
    'Graco',
    'Bugaboo',
    'Stokke',
    'UPPAbaby',
    'Doona',
    'Babyzen',
    'Peg Pérego',
    'Inglesina',
    'Silver Cross',
    'Recaro',
    'Nuna',
    'Baby Jogger',
    'Philips Avent',
    'Tommee Tippee',
    'MAM',
    "Dr. Brown's",
    'NUK',
    'Medela',
    'Munchkin',
    'Skip Hop',
    'Safety 1st',
    'שילב',
    'מטרנה',
    'Similac',
    'Fisher-Price',
    'Tiny Love',
    'Taf Toys',
  ],
  'books': [
    'כתר',
    'עם עובד',
    'זמורה ביתן',
    'כנרת',
    'ידיעות ספרים',
    'מודן',
    'שוקן',
    'הקיבוץ המאוחד',
    'דביר',
    'מטר',
    'אחוזת בית',
    'פן',
    'גרף',
    'ספרית פועלים',
    'אריה ניר',
    'מגיד',
    'סטימצקי',
    'צומת ספרים',
    'Penguin',
    'HarperCollins',
    'Oxford University Press',
    'Marvel',
    'DC Comics',
    'Viz Media',
    'Sony Music',
    'Universal Music',
    'Warner Music',
    'הד ארצי',
    'NMC',
    'הליקון',
    'Disney',
    'Warner Bros.',
    'Paramount',
  ],
  'pets': [
    'Royal Canin',
    "Hill's",
    'Purina',
    'Pro Plan',
    'Pedigree',
    'Whiskas',
    'Acana',
    'Orijen',
    'Brit',
    'Josera',
    'Happy Dog',
    'Farmina',
    'Monge',
    'Eukanuba',
    'Iams',
    'Advance',
    'Bozita',
    'Almo Nature',
    'Applaws',
    'בונזו',
    'לה קט',
    'Trixie',
    'Ferplast',
    'Kong',
    'Flexi',
    'Julius-K9',
    'PetSafe',
    'Savic',
    'Catit',
    'Beaphar',
    'Frontline',
    'Bravecto',
    'Seresto',
    'Eheim',
    'Fluval',
    'Tetra',
  ],
  'services': _kNotApplicableManufacturers,
  'jobs': _kNotApplicableManufacturers,
  'other': _kGenericManufacturers,
};

const Map<String, Map<String, List<String>>> _kManufacturersBySubCategory = {
  'electronics': {
    'smartphones': [
      'Samsung',
      'Apple',
      'Xiaomi',
      'Google',
      'OnePlus',
      'Motorola',
      'Huawei',
      'Honor',
      'Oppo',
      'Vivo',
      'Realme',
      'Poco',
      'Redmi',
      'Nokia',
      'Sony',
      'ZTE',
      'TCL',
      'Nothing',
      'ASUS',
      'Doro',
      'CAT',
      'Alcatel',
    ],
    'laptops': [
      'Apple',
      'Dell',
      'HP',
      'Lenovo',
      'ASUS',
      'Acer',
      'MSI',
      'Microsoft',
      'Samsung',
      'LG',
      'Razer',
      'Gigabyte',
      'Huawei',
      'Dynabook',
      'Fujitsu',
      'Alienware',
      'Framework',
    ],
    'tablets': [
      'Apple',
      'Samsung',
      'Lenovo',
      'Xiaomi',
      'Huawei',
      'Honor',
      'Microsoft',
      'Amazon',
      'Nokia',
      'TCL',
      'Realme',
      'Onyx Boox',
      'Wacom',
      'reMarkable',
    ],
    'headphones': [
      'Apple',
      'Beats',
      'Sony',
      'Bose',
      'Sennheiser',
      'JBL',
      'Samsung',
      'Anker',
      'Soundcore',
      'Jabra',
      'Skullcandy',
      'Marshall',
      'Audio-Technica',
      'AKG',
      'Beyerdynamic',
      'Shure',
      'Logitech',
      'HyperX',
      'SteelSeries',
      'Razer',
      'Xiaomi',
      'Huawei',
      'Nothing',
      'Philips',
    ],
    'cameras': [
      'Canon',
      'Nikon',
      'Sony',
      'Fujifilm',
      'Panasonic',
      'OM System',
      'Olympus',
      'Leica',
      'Ricoh',
      'Pentax',
      'GoPro',
      'DJI',
      'Insta360',
      'Sigma',
      'Tamron',
      'Zeiss',
      'Hasselblad',
      'Blackmagic',
      'Polaroid',
      'Kodak',
      'Manfrotto',
      'Godox',
    ],
    'gaming': [
      'Sony',
      'Microsoft',
      'Nintendo',
      'Valve',
      'Razer',
      'Logitech',
      'HyperX',
      'SteelSeries',
      'Corsair',
      'Turtle Beach',
      'ASUS',
      'MSI',
      'Alienware',
      '8BitDo',
      'Thrustmaster',
      'Meta',
      'NVIDIA',
      'AMD',
      'Elgato',
      'Cooler Master',
    ],
    'tv_audio': [
      'Samsung',
      'LG',
      'Sony',
      'Philips',
      'TCL',
      'Hisense',
      'Xiaomi',
      'Toshiba',
      'Panasonic',
      'Sharp',
      'Haier',
      'נורמנדה',
      'JBL',
      'Bose',
      'Yamaha',
      'Denon',
      'Marantz',
      'Sonos',
      'Harman Kardon',
      'Klipsch',
      'Pioneer',
      'Onkyo',
    ],
    'accessories': [
      'Anker',
      'Belkin',
      'Logitech',
      'Baseus',
      'Ugreen',
      'Spigen',
      'OtterBox',
      'Mophie',
      'Apple',
      'Samsung',
      'Xiaomi',
      'SanDisk',
      'Kingston',
      'Western Digital',
      'Seagate',
      'TP-Link',
      'Netgear',
      'Trust',
      'HP',
      'Aukey',
    ],
  },
  'fashion': {
    'men_clothing': [
      'Zara',
      'H&M',
      'Castro',
      'Fox',
      'Golf',
      'Honigman',
      'Pull&Bear',
      'Bershka',
      'Massimo Dutti',
      'Uniqlo',
      "Levi's",
      'Tommy Hilfiger',
      'Calvin Klein',
      'Ralph Lauren',
      'Lacoste',
      'Hugo Boss',
      'Diesel',
      'Gap',
      'Superdry',
      'Jack & Jones',
      'Nautica',
      'Scotch & Soda',
      'Nike',
      'Adidas',
      'Puma',
      'Under Armour',
      'The North Face',
      'Columbia',
      'Timberland',
      'Delta',
    ],
    'women_clothing': [
      'Zara',
      'H&M',
      'Mango',
      'Castro',
      'Fox',
      'Renuar',
      'Golf',
      'TwentyFourSeven',
      'Pull&Bear',
      'Bershka',
      'Stradivarius',
      'Massimo Dutti',
      'Uniqlo',
      'COS',
      '& Other Stories',
      'Guess',
      'Calvin Klein',
      'Tommy Hilfiger',
      'Michael Kors',
      'Desigual',
      'Vero Moda',
      'Only',
      'Nike',
      'Adidas',
      'Puma',
      'Lululemon',
      "Victoria's Secret",
      'Delta',
    ],
    'shoes': [
      'Nike',
      'Adidas',
      'New Balance',
      'Puma',
      'Converse',
      'Vans',
      'Reebok',
      'ASICS',
      'Saucony',
      'Brooks',
      'Hoka',
      'Salomon',
      'Merrell',
      'Under Armour',
      'Fila',
      'Skechers',
      'Crocs',
      'Birkenstock',
      'Dr. Martens',
      'Timberland',
      'Teva',
      'טבע נאות',
      'Scholl',
      'Geox',
      'Clarks',
      'Ecco',
      'Camper',
      'Steve Madden',
      'Aldo',
      'Palladium',
    ],
    'bags': [
      'Samsonite',
      'American Tourister',
      'Kipling',
      'Eastpak',
      'Herschel',
      'JanSport',
      'The North Face',
      'Osprey',
      'Deuter',
      'Tumi',
      'Delsey',
      'Michael Kors',
      'Guess',
      'Fossil',
      'Coach',
      'Longchamp',
      'Lacoste',
      'Calvin Klein',
      'Nike',
      'Adidas',
      'Under Armour',
      'Case Logic',
      'Targus',
      'Crumpler',
    ],
    'accessories': [
      'Ray-Ban',
      'Oakley',
      'Carrera',
      'Persol',
      'Police',
      'Polaroid',
      'Gucci',
      'Prada',
      'Michael Kors',
      'Fossil',
      'Casio',
      'Seiko',
      'Citizen',
      'Tissot',
      'Swatch',
      'Timex',
      'Daniel Wellington',
      'Garmin',
      'Apple',
      'Samsung',
      'Calvin Klein',
      'Tommy Hilfiger',
      'Hugo Boss',
      'Lacoste',
    ],
    'jewelry': [
      'Pandora',
      'Swarovski',
      'Tiffany & Co.',
      'Cartier',
      'Bvlgari',
      'Thomas Sabo',
      'Michael Kors',
      'Fossil',
      'Calvin Klein',
      'Guess',
      'Daniel Wellington',
      'Folli Follie',
      'Emporio Armani',
      'פדני',
      'מגנוליה',
      'ה. שטרן',
      'אורו',
    ],
  },
  'vehicles': {
    'cars': [
      'Toyota',
      'Mazda',
      'Hyundai',
      'Kia',
      'Skoda',
      'Volkswagen',
      'Nissan',
      'Honda',
      'Mitsubishi',
      'Suzuki',
      'Renault',
      'Peugeot',
      'Citroën',
      'Seat',
      'Cupra',
      'Ford',
      'Chevrolet',
      'Opel',
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Volvo',
      'Subaru',
      'Jeep',
      'Tesla',
      'MG',
      'BYD',
      'Chery',
      'Geely',
      'Lexus',
      'Mini',
      'Fiat',
      'Alfa Romeo',
      'Dacia',
      'Land Rover',
      'Porsche',
      'Isuzu',
      'SsangYong',
    ],
    'motorcycles': [
      'Honda',
      'Yamaha',
      'Suzuki',
      'Kawasaki',
      'BMW',
      'KTM',
      'Ducati',
      'Harley-Davidson',
      'Triumph',
      'Aprilia',
      'Piaggio',
      'Vespa',
      'SYM',
      'Kymco',
      'Peugeot',
      'Benelli',
      'Royal Enfield',
      'CFMoto',
      'Husqvarna',
      'Keeway',
      'Daelim',
      'Zontes',
    ],
    'bicycles': [
      'Trek',
      'Giant',
      'Specialized',
      'Scott',
      'Merida',
      'Cannondale',
      'Cube',
      'BMC',
      'Bianchi',
      'Canyon',
      'Orbea',
      'Focus',
      'Ghost',
      'GT',
      'Kona',
      'Santa Cruz',
      'Haibike',
      'Rockrider',
      'B-Twin',
      'Shimano',
    ],
    'scooters': [
      'Xiaomi',
      'Segway-Ninebot',
      'Inokim',
      'Kaabo',
      'Dualtron',
      'Vsett',
      'Zero',
      'Apollo',
      'NIU',
      'Razor',
      'Micro',
      'E-Twow',
      'Yadea',
      'Joyor',
      'Speedway',
      'Smartway',
    ],
    'parts': [
      'Bosch',
      'Denso',
      'NGK',
      'Brembo',
      'Mann-Filter',
      'Mahle',
      'Valeo',
      'SKF',
      'Sachs',
      'Monroe',
      'Bilstein',
      'KYB',
      'Gates',
      'Continental',
      'Michelin',
      'Bridgestone',
      'Pirelli',
      'Goodyear',
      'Hankook',
      'Toyo',
      'Varta',
      'Exide',
      'Optima',
      'Castrol',
      'Mobil',
      'Shell',
    ],
    'accessories': [
      'Thule',
      'Yakima',
      'Bosch',
      'Philips',
      'Osram',
      'Garmin',
      'Baseus',
      'Anker',
      'Pioneer',
      'JVC',
      'Kenwood',
      'Alpine',
      'Sony',
      'Momo',
      'Sparco',
      'WeatherTech',
      '3M',
      'Kärcher',
      "Meguiar's",
      'Turtle Wax',
    ],
  },
  'home_garden': {
    'appliances': [
      'אלקטרה',
      'תדיראן',
      'טורנדו',
      'סאוטר',
      'נורמנדה',
      'אמקור',
      'קריסטל',
      'בלומברג',
      'Beko',
      'Bosch',
      'Siemens',
      'Samsung',
      'LG',
      'Whirlpool',
      'Electrolux',
      'AEG',
      'Miele',
      'Candy',
      'Hoover',
      'Indesit',
      'Ariston',
      'Zanussi',
      'Sharp',
      'Toshiba',
      'Haier',
      'Hisense',
      'Midea',
      'Gree',
      'Hyundai',
      'Philips',
      'Braun',
      'Kenwood',
      'KitchenAid',
      'Moulinex',
      'Tefal',
      'DeLonghi',
      'Nespresso',
      'SodaStream',
      'Dyson',
    ],
    'tools': [
      'Bosch',
      'Makita',
      'DeWalt',
      'Hilti',
      'Ryobi',
      'Milwaukee',
      'Metabo',
      'Festool',
      'Stanley',
      'Black+Decker',
      'Einhell',
      'HiKOKI',
      'AEG',
      'Skil',
      'Worx',
      'Dremel',
      'Knipex',
      'Wera',
      'Wiha',
      'Irwin',
      'Bahco',
      'Fiskars',
      'Kärcher',
      'Total',
      'Ingco',
      'Crown',
    ],
    'kitchen': [
      'Tefal',
      'Fissler',
      'WMF',
      'Zwilling',
      'Henckels',
      'Victorinox',
      'Global',
      'Le Creuset',
      'Staub',
      'Lodge',
      'Pyrex',
      'Corelle',
      'Duralex',
      'נעמן',
      'Bodum',
      'Kenwood',
      'KitchenAid',
      'Bosch',
      'Philips',
      'Braun',
      'Moulinex',
      'DeLonghi',
      'Nespresso',
      'SodaStream',
      'Tupperware',
      'Sistema',
      'OXO',
      'Brabantia',
      'Joseph Joseph',
      'BergHOFF',
    ],
    'garden': [
      'Gardena',
      'Husqvarna',
      'Fiskars',
      'Stihl',
      'Bosch',
      'Einhell',
      'Ryobi',
      'Makita',
      'Kärcher',
      'Greenworks',
      'AL-KO',
      'Wolf-Garten',
      'Flymo',
      'Hozelock',
      'Rain Bird',
      'Hunter',
      'Toro',
      'נטפים',
      'פלסטרו',
      'כתר',
    ],
    'decor': [
      'IKEA',
      'Philips',
      'Osram',
      'Ledvance',
      'Eglo',
      'Paulmann',
      'Nordlux',
      'Artemide',
      'Flos',
      'Louis Poulsen',
      'Tom Dixon',
      'Muuto',
      'HAY',
      'Umbra',
      'Yankee Candle',
      'Zara Home',
      'H&M Home',
      'כתר',
      'ביתילי',
      'הום סנטר',
    ],
    'storage': [
      'כתר',
      'IKEA',
      'ביתילי',
      'הום סנטר',
      'Sistema',
      'Tupperware',
      'Curver',
      'Really Useful Box',
      'Brabantia',
      'Elfa',
      'Stanley',
      'Plano',
      'Rubbermaid',
      'Sterilite',
      'Joseph Joseph',
      'Samla',
    ],
  },
  'fashion_beauty': {
    'makeup': [
      "L'Oréal",
      'Maybelline',
      'NYX',
      'MAC',
      'Revlon',
      'Essence',
      'Catrice',
      'Rimmel',
      'Max Factor',
      'Bourjois',
      'Estée Lauder',
      'Clinique',
      'Lancôme',
      'Dior',
      'Chanel',
      'Yves Saint Laurent',
      'Charlotte Tilbury',
      'Fenty Beauty',
      'Huda Beauty',
      'Benefit',
      'Urban Decay',
      'Too Faced',
      'e.l.f.',
      'Morphe',
      'Anastasia Beverly Hills',
      'Kiko Milano',
      'Pupa',
      'קרליין',
      'Sephora',
    ],
    'skincare': [
      'CeraVe',
      'The Ordinary',
      'La Roche-Posay',
      'Vichy',
      'Bioderma',
      'Avène',
      'Eucerin',
      'Neutrogena',
      'Nivea',
      'Garnier',
      "L'Oréal",
      'Clinique',
      'Estée Lauder',
      'Lancôme',
      'Clarins',
      'Shiseido',
      "Kiehl's",
      'Olay',
      'Aveeno',
      'Cetaphil',
      'Bio-Oil',
      "Paula's Choice",
      'Drunk Elephant',
      'אהבה',
      'כריסטינא',
      'Anna Lotan',
      'ד״ר פישר',
      'קרליין',
      'סבון',
      'ליין',
    ],
    'haircare': [
      'Gillette',
      'Braun',
      'Philips',
      'Panasonic',
      'Remington',
      'Wahl',
      'Andis',
      'BaByliss',
      'Dyson',
      'GHD',
      'Revlon',
      'Moroccanoil',
      'Kérastase',
      'Wella',
      'Schwarzkopf',
      "L'Oréal",
      'Pantene',
      'Head & Shoulders',
      'Herbal Essences',
      'TRESemmé',
      'John Frieda',
      'OGX',
      'Olaplex',
      'Nivea',
      'Garnier',
      'לייף',
      'ד״ר פישר',
    ],
    'perfumes': [
      'Dior',
      'Chanel',
      'Yves Saint Laurent',
      'Gucci',
      'Versace',
      'Giorgio Armani',
      'Paco Rabanne',
      'Jean Paul Gaultier',
      'Calvin Klein',
      'Hugo Boss',
      'Dolce & Gabbana',
      'Lancôme',
      'Givenchy',
      'Burberry',
      'Prada',
      'Tom Ford',
      'Creed',
      'Montale',
      'Lattafa',
      'Bvlgari',
      'Hermès',
      'Carolina Herrera',
      'Narciso Rodriguez',
      'Viktor&Rolf',
      'Mugler',
      'Zara',
      'The Body Shop',
      'סבון',
      'ליין',
    ],
    'health': [
      'Solgar',
      'אלטמן',
      'סופהרב',
      'Now Foods',
      'Centrum',
      "Nature's Bounty",
      'Jarrow',
      "Doctor's Best",
      'Garden of Life',
      'Optimum Nutrition',
      'MyProtein',
      'Scitec',
      'BSN',
      'Herbalife',
      'טבע',
      'Omron',
      'Beurer',
      'Medisana',
      'Microlife',
      'Braun',
      'Accu-Chek',
      'Contour',
    ],
  },
  'sports': {
    'gym_equipment': [
      'Technogym',
      'Life Fitness',
      'Matrix',
      'Precor',
      'NordicTrack',
      'ProForm',
      'Bowflex',
      'Domyos',
      'Reebok',
      'Everlast',
      'Kettler',
      'Hammer',
      'Sole',
      'Horizon',
      'Schwinn',
      'Concept2',
      'Rogue',
      'Eleiko',
      'Xterra',
      'Peloton',
      'Keiser',
    ],
    'bikes': [
      'Trek',
      'Giant',
      'Specialized',
      'Scott',
      'Merida',
      'Cannondale',
      'Cube',
      'BMC',
      'Bianchi',
      'Canyon',
      'Orbea',
      'Focus',
      'Ghost',
      'GT',
      'Kona',
      'Santa Cruz',
      'Haibike',
      'Rockrider',
      'B-Twin',
      'Shimano',
    ],
    'outdoor': [
      'The North Face',
      'Columbia',
      'Salomon',
      'Merrell',
      'Quechua',
      'Forclaz',
      'Deuter',
      'Osprey',
      'Jack Wolfskin',
      'Mammut',
      'Black Diamond',
      'Petzl',
      'MSR',
      'Coleman',
      'Sea to Summit',
      'Therm-a-Rest',
      'Nalgene',
      'Leatherman',
      'Victorinox',
      'Garmin',
      'Suunto',
      'Hi-Tec',
      'Timberland',
      'CamelBak',
    ],
    'water_sports': [
      'Speedo',
      'Arena',
      'TYR',
      'Zoggs',
      'Aqua Sphere',
      'Cressi',
      'Mares',
      'Scubapro',
      'Aqualung',
      'Beuchat',
      "O'Neill",
      'Rip Curl',
      'Quiksilver',
      'Billabong',
      'Body Glove',
      'Naish',
      'Duotone',
      'Cabrinha',
      'F-One',
      'Starboard',
      'Red Paddle',
      'Decathlon',
    ],
    'winter_sports': [
      'Salomon',
      'Atomic',
      'Rossignol',
      'Head',
      'Fischer',
      'Völkl',
      'K2',
      'Nordica',
      'Elan',
      'Blizzard',
      'Burton',
      'Dynastar',
      'Scott',
      'Giro',
      'POC',
      'Smith',
      'Oakley',
      'Leki',
      'Dalbello',
      'Tecnica',
      'Columbia',
      'The North Face',
      'Wedze',
    ],
    'sportswear': [
      'Nike',
      'Adidas',
      'Puma',
      'Under Armour',
      'Reebok',
      'New Balance',
      'ASICS',
      'Lululemon',
      'Gymshark',
      'Champion',
      'Fila',
      'Kappa',
      'Umbro',
      'Joma',
      'Macron',
      'Mizuno',
      'Skechers',
      'Columbia',
      'The North Face',
      'Kalenji',
      'Everlast',
      'Venum',
      'Delta',
    ],
  },
  'toys': {
    'baby_toys': [
      'Fisher-Price',
      'VTech',
      'Chicco',
      'Tiny Love',
      'Taf Toys',
      'Lamaze',
      'Bright Starts',
      'Playgro',
      'Skip Hop',
      'Baby Einstein',
      'Sophie la Girafe',
      'Melissa & Doug',
      'Hape',
      'Manhattan Toy',
      'Infantino',
      'Munchkin',
      'Little Tikes',
      'Clementoni',
    ],
    'video_games': [
      'Nintendo',
      'Sony',
      'Microsoft',
      'EA',
      'Ubisoft',
      'Activision',
      'Rockstar Games',
      'Bethesda',
      'Square Enix',
      'Capcom',
      'Konami',
      'Sega',
      '2K',
      'Bandai Namco',
      'Valve',
      'Epic Games',
      'CD Projekt',
      'Warner Bros. Games',
      'THQ Nordic',
      'Take-Two',
    ],
  },
  'kids': {
    'strollers': [
      'Chicco',
      'Maxi-Cosi',
      'Britax',
      'Cybex',
      'Joie',
      'Graco',
      'Bugaboo',
      'Stokke',
      'UPPAbaby',
      'Doona',
      'Babyzen',
      'Peg Pérego',
      'Inglesina',
      'Silver Cross',
      'Nuna',
      'Baby Jogger',
      'Phil & Teds',
      'Mima',
      'שילב',
    ],
    'car_seats': [
      'Maxi-Cosi',
      'Britax',
      'Cybex',
      'Chicco',
      'Joie',
      'Graco',
      'Doona',
      'Recaro',
      'Nuna',
      'Peg Pérego',
      'Safety 1st',
      'BeSafe',
      'Kiddy',
      'Diono',
      'Evenflo',
      'שילב',
    ],
    'feeding': [
      'Philips Avent',
      'Tommee Tippee',
      'MAM',
      "Dr. Brown's",
      'NUK',
      'Medela',
      'Chicco',
      'Munchkin',
      'Lansinoh',
      'Nuby',
      'Bibi',
      'Elvie',
      'מטרנה',
      'Similac',
      'Nutrilon',
      'Nestlé',
      'Beaba',
      'Babymoov',
    ],
    'kids_clothing': [
      'Castro',
      'Fox',
      'Zara',
      'H&M',
      'Next',
      "Carter's",
      "OshKosh B'gosh",
      'Gap',
      'Mothercare',
      'Okaidi',
      'TwentyFourSeven',
      'Nike',
      'Adidas',
      'Puma',
      'Disney',
      'Crocs',
      'Skechers',
      'Delta',
    ],
  },
  'pets': {
    'food': [
      'Royal Canin',
      "Hill's",
      'Purina',
      'Pro Plan',
      'Pedigree',
      'Whiskas',
      'Acana',
      'Orijen',
      'Brit',
      'Josera',
      'Happy Dog',
      'Farmina',
      'Monge',
      'Eukanuba',
      'Iams',
      'Advance',
      'Bozita',
      'Almo Nature',
      'Applaws',
      'בונזו',
      'לה קט',
      'Tetra',
    ],
    'accessories': [
      'Trixie',
      'Ferplast',
      'Kong',
      'Flexi',
      'Julius-K9',
      'PetSafe',
      'Savic',
      'Catit',
      'Hagen',
      'Zolux',
      'Beaphar',
      'Curver',
      'Eheim',
      'Fluval',
      'Tetra',
      'JBL',
      'Sera',
      'Karlie',
      'Rogz',
      'Nobby',
    ],
  },
};

Map<String, List<String>> _learnedByCategory = const <String, List<String>>{};

int _learnedVersion = 0;

int get learnedManufacturersVersion => _learnedVersion;

bool applyLearnedManufacturers(Map<String, dynamic>? docData) {
  if (docData == null) return false;

  final version = (docData['version'] as num?)?.toInt() ?? 0;
  if (version != 0 && version == _learnedVersion) return false;

  final rawEntries = docData['entries'];
  if (rawEntries is! List) return false;

  final grouped = <String, List<String>>{};
  for (final raw in rawEntries) {
    if (raw is! Map) continue;
    final name = (raw['name'] as String?)?.trim();
    final categoryId = (raw['categoryId'] as String?)?.trim();
    if (name == null || name.isEmpty) continue;
    if (categoryId == null || categoryId.isEmpty) continue;
    if (name == kOtherManufacturer) continue;
    (grouped[categoryId] ??= <String>[]).add(name);
  }

  _learnedByCategory = grouped;
  _learnedVersion = version;
  return true;
}

List<String> manufacturersFor({
  required String? categoryId,
  String? subCategoryId,
}) {
  final List<String> base =
      _kManufacturersBySubCategory[categoryId]?[subCategoryId] ??
      _kManufacturersByCategory[categoryId] ??
      _kGenericManufacturers;

  final result = <String>[];
  final seen = <String>{};
  final seenNormalized = <String>{};
  for (final name in base) {
    if (name == kOtherManufacturer) continue;
    if (seen.add(name)) {
      result.add(name);
      seenNormalized.add(_normalizeManufacturer(name));
    }
  }

  for (final name in _learnedByCategory[categoryId] ?? const <String>[]) {
    if (seenNormalized.add(_normalizeManufacturer(name))) result.add(name);
  }

  result.add(kOtherManufacturer);
  return result;
}

String? matchManufacturer(String? rawName, List<String> options) {
  final normalized = _normalizeManufacturer(rawName);
  if (normalized.isEmpty) return null;
  for (final option in options) {
    if (option == kOtherManufacturer) continue;
    if (_normalizeManufacturer(option) == normalized) return option;
  }
  return null;
}

String normalizeManufacturerName(String? value) =>
    _normalizeManufacturer(value);

const Map<String, String> _kLatinAccentFolding = {
  'á': 'a',
  'à': 'a',
  'â': 'a',
  'ä': 'a',
  'ã': 'a',
  'å': 'a',
  'é': 'e',
  'è': 'e',
  'ê': 'e',
  'ë': 'e',
  'í': 'i',
  'ì': 'i',
  'î': 'i',
  'ï': 'i',
  'ó': 'o',
  'ò': 'o',
  'ô': 'o',
  'ö': 'o',
  'õ': 'o',
  'ø': 'o',
  'ú': 'u',
  'ù': 'u',
  'û': 'u',
  'ü': 'u',
  'ñ': 'n',
  'ç': 'c',
  'ß': 'ss',
  'æ': 'ae',
};

String _normalizeManufacturer(String? value) {
  if (value == null) return '';
  final buffer = StringBuffer();
  for (final char in value.toLowerCase().split('')) {
    buffer.write(_kLatinAccentFolding[char] ?? char);
  }
  return buffer.toString().replaceAll(RegExp(r'[^a-z0-9א-ת]'), '');
}
